### ISSUE TITLE
[REDACTED]

### ISSUE THREAD

**Issue by YukiSoha** [Commoble/hyperbox#21]

**Comment by Commoble** [comment]
I used to use random strings but I changed it to match the name of the hyperbox at the request of server ops to make it easier to identify which hyperbox dimension folder is which

But yeah, it should be stricter and not allow `.` in the ids. Can probably make it generate a legit-but-readable id from the display name instead of letting the user pick both the id and the name. Should be able to push fixes out later tonight.

**Comment by YukiSoha** [comment]
Best thing is to just whitelist A-Z/a-z/0-9 and replace all other characters with _ or something in that case

**Comment by Commoble** [comment]
Fixed in 1.20.4-5.0.1.0. Also backported fix to 1.20.1-4.0.2.0.
